// Fictional Siesta catalog. All names, prices and descriptions are original.
// No reviews/ratings are fabricated — review slots stay empty until verified purchases exist.
export const CATEGORIES = [
  { id: "tshirts", label: "T-Shirts", blurb: "Heavyweight cottons, clean cuts" },
  { id: "shirts", label: "Shirts", blurb: "Oxfords, flannels & resort shirts" },
  { id: "jackets", label: "Jackets", blurb: "Utility, denim & windbreakers" },
  { id: "hoodies", label: "Hoodies", blurb: "Brushed fleece, relaxed fits" },
  { id: "jeans", label: "Jeans", blurb: "Straight, slim & relaxed denim" },
  { id: "pants", label: "Pants", blurb: "Cargos, chinos & trousers" },
  { id: "shorts", label: "Shorts", blurb: "Everyday & athletic shorts" },
  { id: "sweatshirts", label: "Sweatshirts", blurb: "Crewnecks & quarter-zips" },
];

export const COUPONS = [
  { code: "WELCOME10", type: "pct", value: 10, minSubtotal: 999, expires: "2027-03-31", label: "10% off on orders over ₹999" },
  { code: "SIESTA15", type: "pct", value: 15, minSubtotal: 1999, expires: "2027-06-30", label: "15% off on orders over ₹1,999" },
  { code: "FLAT200", type: "flat", value: 200, minSubtotal: 1499, expires: "2027-02-28", label: "₹200 off on orders over ₹1,499" },
  { code: "EXPIRED5", type: "pct", value: 5, minSubtotal: 500, expires: "2024-01-01", label: "Expired test coupon" },
];

const P = (o) => o;
export const PRODUCTS = [
  P({ id:"tee-essential-oversized", name:"Essential Oversized Tee", category:"tshirts", gender:"unisex", price:799, mrp:1199, colors:[{name:"Ecru",hex:"#E8E0D2"}], sizes:["S","M","L","XL"], stock:14, sku:"SS-TS-001", material:"100% combed cotton, 220 GSM", care:"Machine wash cold, inside out. Do not bleach. Tumble dry low.", isNew:true, bestseller:true, added:"2026-07-02", popularity:98, desc:"Our signature heavyweight tee with a clean dropped shoulder and a collar that keeps its shape. Cut slightly oversized for an easy, everyday drape.", details:["220 GSM combed cotton","Ribbed crew neckline","Side-seamed, pre-shrunk","Made for everyday wear"] }),
  P({ id:"tee-everyday-pocket", name:"Everyday Pocket Tee", category:"tshirts", gender:"men", price:699, mrp:999, colors:[{name:"Sand",hex:"#D9CBB6"}], sizes:["S","M","L","XL","XXL"], stock:22, sku:"SS-TS-002", material:"100% cotton jersey", care:"Machine wash cold with like colours.", isNew:false, bestseller:true, added:"2026-03-14", popularity:91, desc:"A workwear-inspired pocket tee in breathable jersey. Garment-washed for softness from the first wear.", details:["Chest patch pocket","Garment washed","Regular fit"] }),
  P({ id:"tee-ribbed-henley", name:"Ribbed Long-Sleeve Henley", category:"tshirts", gender:"men", price:999, mrp:1499, colors:[{name:"Oat",hex:"#E5DCC8"}], sizes:["M","L","XL"], stock:9, sku:"SS-TS-003", material:"Cotton-modal rib", care:"Wash cold, dry flat in shade.", isNew:true, bestseller:false, added:"2026-08-01", popularity:76, desc:"A textured rib henley with coconut buttons. Layers cleanly under overshirts through the cooler months.", details:["Three-button placket","Coconut buttons","Slim-regular fit"] }),
  P({ id:"tee-cropped-women", name:"Soft Cropped Tee", category:"tshirts", gender:"women", price:749, mrp:1099, colors:[{name:"Blush",hex:"#E4C4B8"}], sizes:["XS","S","M","L"], stock:18, sku:"SS-TS-004", material:"Cotton-elastane jersey", care:"Machine wash cold, reshape while damp.", isNew:true, bestseller:false, added:"2026-07-20", popularity:82, desc:"A gently cropped tee with a touch of stretch. Sits neatly at the waist of high-rise denim.", details:["Cropped length","Crew neck","Slight stretch"] }),
  P({ id:"tee-striped-breton", name:"Breton Stripe Tee", category:"tshirts", gender:"unisex", price:899, mrp:1299, colors:[{name:"Navy/Ecru",hex:"#2B3A55"}], sizes:["S","M","L","XL"], stock:11, sku:"SS-TS-005", material:"100% combed cotton", care:"Wash inside out to protect stripes.", isNew:false, bestseller:false, added:"2026-04-02", popularity:70, desc:"A timeless Breton stripe knitted — not printed — so the lines stay crisp wash after wash.", details:["Yarn-dyed stripes","Classic fit","Made to last"] }),

  P({ id:"shirt-relaxed-oxford", name:"Relaxed Oxford Shirt", category:"shirts", gender:"men", price:1499, mrp:2199, colors:[{name:"Sky",hex:"#B9CDDE"}], sizes:["S","M","L","XL","XXL"], stock:16, sku:"SS-SH-001", material:"Cotton oxford weave", care:"Machine wash warm, warm iron.", isNew:false, bestseller:true, added:"2026-02-11", popularity:94, desc:"A breathable oxford with a relaxed body and single chest pocket. Equally at home tucked or untucked.", details:["Button-down collar","Single pocket","Relaxed fit"] }),
  P({ id:"shirt-brushed-flannel", name:"Brushed Check Flannel", category:"shirts", gender:"men", price:1599, mrp:2299, colors:[{name:"Rust Check",hex:"#9A4A2E"}], sizes:["M","L","XL"], stock:7, sku:"SS-SH-002", material:"Brushed cotton flannel", care:"Machine wash cold, tumble low.", isNew:false, bestseller:false, added:"2026-05-06", popularity:68, desc:"Double-brushed for a soft hand, in a muted check that pairs with raw denim and boots.", details:["Yarn-dyed check","Curved hem","Regular fit"] }),
  P({ id:"shirt-resort-camp", name:"Resort Camp-Collar Shirt", category:"shirts", gender:"unisex", price:1399, mrp:1999, colors:[{name:"Sand",hex:"#D9CBB6"}], sizes:["S","M","L","XL"], stock:13, sku:"SS-SH-003", material:"Tencel-cotton twill", care:"Gentle wash, cool iron.", isNew:true, bestseller:false, added:"2026-07-28", popularity:80, desc:"An open camp collar and fluid drape make this the easiest warm-weather shirt we cut.", details:["Camp collar","Straight hem","Relaxed drape"] }),
  P({ id:"shirt-poplin-women", name:"Crisp Poplin Shirt", category:"shirts", gender:"women", price:1449, mrp:2099, colors:[{name:"White",hex:"#F6F4EF"}], sizes:["XS","S","M","L","XL"], stock:19, sku:"SS-SH-004", material:"Compact cotton poplin", care:"Machine wash, warm iron.", isNew:false, bestseller:true, added:"2026-03-30", popularity:89, desc:"A sharp, breathable poplin with a slightly relaxed body — office-ready, weekend-easy.", details:["Mother-of-pearl style buttons","Back yoke pleat","Relaxed fit"] }),
  P({ id:"shirt-denim-western", name:"Washed Denim Shirt", category:"shirts", gender:"men", price:1699, mrp:2499, colors:[{name:"Mid Wash",hex:"#5B7A9A"}], sizes:["S","M","L","XL"], stock:6, sku:"SS-SH-005", material:"8 oz cotton denim", care:"Wash cold with like colours; indigo may transfer.", isNew:false, bestseller:false, added:"2026-01-18", popularity:66, desc:"A mid-weight denim shirt, enzyme-washed for softness with contrast stitching.", details:["Western yokes","Snap-style buttons","Regular fit"] }),

  P({ id:"jacket-urban-utility", name:"Urban Utility Jacket", category:"jackets", gender:"men", price:2999, mrp:4499, colors:[{name:"Olive",hex:"#5A6248"}], sizes:["M","L","XL","XXL"], stock:8, sku:"SS-JK-001", material:"Cotton-nylon ripstop", care:"Spot clean, gentle wash when needed.", isNew:true, bestseller:true, added:"2026-08-05", popularity:96, desc:"Four-pocket utility shell with a water-repellent finish. Roomy enough for a hoodie underneath.", details:["Water-repellent finish","4 utility pockets","Drawcord hem"] }),
  P({ id:"jacket-denim-trucker", name:"Classic Denim Trucker", category:"jackets", gender:"unisex", price:2799, mrp:3999, colors:[{name:"Vintage Wash",hex:"#6B8AA8"}], sizes:["S","M","L","XL"], stock:10, sku:"SS-JK-002", material:"12 oz cotton denim", care:"Wash infrequently, cold.", isNew:false, bestseller:true, added:"2026-02-22", popularity:90, desc:"Our take on the timeless trucker — structured shoulders, slightly boxy body, built to break in beautifully.", details:["Copper shanks","Two chest pockets","Boxy-regular fit"] }),
  P({ id:"jacket-feather-wind", name:"Featherweight Windbreaker", category:"jackets", gender:"unisex", price:2199, mrp:3199, colors:[{name:"Stone",hex:"#D5CDBD"}], sizes:["S","M","L","XL"], stock:15, sku:"SS-JK-003", material:"Recycled nylon taslan", care:"Machine wash cold, hang dry.", isNew:true, bestseller:false, added:"2026-07-11", popularity:78, desc:"Packs into its own pocket. A featherlight layer for sudden showers and windy evenings.", details:["Packable hood","Elastic cuffs","Water-resistant"] }),
  P({ id:"jacket-quilted-overshirt", name:"Quilted Field Overshirt", category:"jackets", gender:"women", price:2899, mrp:4199, colors:[{name:"Espresso",hex:"#4A342E"}], sizes:["XS","S","M","L"], stock:5, sku:"SS-JK-004", material:"Cotton shell, recycled fill", care:"Gentle wash, tumble low.", isNew:true, bestseller:false, added:"2026-08-10", popularity:74, desc:"A lightly insulated overshirt-jacket hybrid with diamond quilting and patch pockets.", details:["Light insulation","Corduroy collar","Relaxed fit"] }),

  P({ id:"hood-classic-fleece", name:"Classic Brushed Hoodie", category:"hoodies", gender:"unisex", price:1699, mrp:2499, colors:[{name:"Grey Marl",hex:"#9A9A9A"}], sizes:["S","M","L","XL","XXL"], stock:20, sku:"SS-HD-001", material:"400 GSM cotton fleece", care:"Wash cold inside out.", isNew:false, bestseller:true, added:"2026-01-30", popularity:95, desc:"Dense, brushed-back fleece with a double-layer hood. The hoodie we would keep if we could only keep one.", details:["400 GSM fleece","Kangaroo pocket","Ribbed cuffs"] }),
  P({ id:"hood-boxy-women", name:"Boxy Cloud Hoodie", category:"hoodies", gender:"women", price:1599, mrp:2299, colors:[{name:"Lilac Grey",hex:"#B8B2C4"}], sizes:["XS","S","M","L"], stock:12, sku:"SS-HD-002", material:"Cotton-poly fleece", care:"Machine wash cold.", isNew:true, bestseller:false, added:"2026-07-15", popularity:81, desc:"A cropped-boxy cut with dropped shoulders and a silky-soft interior.", details:["Boxy cropped fit","Tonal drawcords","Ultra-soft hand"] }),
  P({ id:"hood-zip-performance", name:"Everyday Zip Hoodie", category:"hoodies", gender:"men", price:1899, mrp:2799, colors:[{name:"Charcoal",hex:"#333333"}], sizes:["M","L","XL"], stock:0, sku:"SS-HD-003", material:"Cotton-blend loopback", care:"Wash cold, zip closed.", isNew:false, bestseller:false, added:"2026-04-20", popularity:64, desc:"A full-zip layer in smooth loopback — structured enough for travel, soft enough for rest days.", details:["Full zip","Side pockets","Regular fit"], outNote:"Restocking soon" }),

  P({ id:"jean-straight-classic", name:"Classic Straight Jeans", category:"jeans", gender:"men", price:1999, mrp:2999, colors:[{name:"Indigo Rinse",hex:"#2E4055"}], sizes:["28","30","32","34","36"], stock:17, sku:"SS-JN-001", material:"98% cotton, 2% elastane, 12.5 oz denim", care:"Wash cold, hang dry.", isNew:false, bestseller:true, added:"2026-02-05", popularity:93, desc:"A true straight leg with a mid rise. Rigid look, with just enough stretch to move.", details:["Mid rise","Straight leg","Zip fly"] }),
  P({ id:"jean-relaxed-women", name:"Relaxed High-Rise Jeans", category:"jeans", gender:"women", price:2099, mrp:3099, colors:[{name:"Ecru Wash",hex:"#D9D2C2"}], sizes:["26","28","30","32"], stock:9, sku:"SS-JN-002", material:"100% cotton denim", care:"Wash cold inside out.", isNew:true, bestseller:false, added:"2026-07-25", popularity:84, desc:"High rise, relaxed through the leg, with a clean cropped hem that shows off sneakers.", details:["High rise","Relaxed leg","Cropped hem"] }),
  P({ id:"jean-slim-onyx", name:"Slim Onyx Jeans", category:"jeans", gender:"men", price:1899, mrp:2799, colors:[{name:"Onyx",hex:"#1E1E1E"}], sizes:["30","32","34"], stock:4, sku:"SS-JN-003", material:"Stretch selvedge-style denim", care:"Wash sparingly.", isNew:false, bestseller:false, added:"2026-05-19", popularity:69, desc:"A sharp black slim with lasting colour retention and a clean, minimal finish.", details:["Stay-black dye","Slim leg","Mid rise"] }),
  P({ id:"jean-wide-women", name:"Wide-Leg Garden Jean", category:"jeans", gender:"women", price:2199, mrp:3299, colors:[{name:"Light Wash",hex:"#9DB4C8"}], sizes:["26","28","30","32"], stock:7, sku:"SS-JN-004", material:"Cotton-linen denim", care:"Machine wash cold.", isNew:true, bestseller:false, added:"2026-08-03", popularity:77, desc:"An airy wide leg in a breathable cotton-linen denim. Made for long summer days.", details:["Wide leg","High rise","Breathable weave"] }),

  P({ id:"pant-cargo-everyday", name:"Everyday Cargo Pants", category:"pants", gender:"men", price:1799, mrp:2599, colors:[{name:"Khaki",hex:"#B5A586"}], sizes:["30","32","34","36"], stock:13, sku:"SS-PN-001", material:"Cotton ripstop twill", care:"Machine wash cold.", isNew:false, bestseller:true, added:"2026-03-08", popularity:88, desc:"Six pockets, tapered leg, adjustable hems. Utility without the bulk.", details:["6 pockets","Tapered leg","Drawcord hem"] }),
  P({ id:"pant-pleated-trouser", name:"Pleated Tailored Trouser", category:"pants", gender:"unisex", price:1999, mrp:2999, colors:[{name:"Charcoal",hex:"#3A3A3A"}], sizes:["S","M","L","XL"], stock:10, sku:"SS-PN-002", material:"TR stretch suiting", care:"Machine wash gentle, cool iron.", isNew:true, bestseller:false, added:"2026-07-08", popularity:79, desc:"A single-pleat trouser with a cropped taper — sharp with loafers, easy with sneakers.", details:["Single pleat","Cropped taper","Hook-and-bar closure"] }),
  P({ id:"pant-linen-drawstring", name:"Linen-Blend Drawstring Pant", category:"pants", gender:"women", price:1699, mrp:2499, colors:[{name:"Ivory",hex:"#F1EAD9"}], sizes:["XS","S","M","L"], stock:11, sku:"SS-PN-003", material:"Linen-cotton blend", care:"Gentle wash, line dry.", isNew:false, bestseller:false, added:"2026-04-28", popularity:71, desc:"Pull-on ease in a breathable weave, with a clean tapered silhouette.", details:["Elastic + drawcord","Side pockets","Tapered leg"] }),
  P({ id:"pant-chino-slim", name:"Slim Stretch Chino", category:"pants", gender:"men", price:1599, mrp:2299, colors:[{name:"Navy",hex:"#2B3A55"}], sizes:["30","32","34","36"], stock:21, sku:"SS-PN-004", material:"Cotton-elastane twill", care:"Machine wash warm.", isNew:false, bestseller:false, added:"2026-02-14", popularity:73, desc:"The weekday workhorse — wrinkle-resistant twill with all-day stretch.", details:["Wrinkle resistant","Stretch twill","Slim fit"] }),

  P({ id:"short-everyday-5", name:"Everyday 5\" Shorts", category:"shorts", gender:"men", price:999, mrp:1499, colors:[{name:"Sand",hex:"#D9CBB6"}], sizes:["S","M","L","XL"], stock:24, sku:"SS-SO-001", material:"Quick-dry nylon-cotton", care:"Machine wash cold.", isNew:false, bestseller:true, added:"2026-03-22", popularity:87, desc:"A versatile 5-inch inseam with elastic back waist — swim-to-street friendly.", details:['5" inseam',"Elastic back waist","Side + back pockets"] }),
  P({ id:"short-pleated-women", name:"Pleated City Shorts", category:"shorts", gender:"women", price:1099, mrp:1599, colors:[{name:"Black",hex:"#1E1E1E"}], sizes:["XS","S","M","L"], stock:16, sku:"SS-SO-002", material:"Viscose-linen blend", care:"Gentle wash.", isNew:true, bestseller:false, added:"2026-06-18", popularity:75, desc:"Tailored pleats and a high rise make these read polished, not sporty.", details:["High rise","Front pleats","Lined waistband"] }),
  P({ id:"short-fleece-lounge", name:"Lounge Fleece Shorts", category:"shorts", gender:"unisex", price:799, mrp:1199, colors:[{name:"Grey",hex:"#9A9A9A"}], sizes:["S","M","L","XL"], stock:26, sku:"SS-SO-003", material:"Loopback cotton fleece", care:"Machine wash cold.", isNew:false, bestseller:false, added:"2026-05-02", popularity:67, desc:"Buttery loopback shorts for slow mornings and evening walks.", details:["Drawcord waist","Side pockets","Above-knee"] }),

  P({ id:"sweat-crew-classic", name:"Classic Crew Sweatshirt", category:"sweatshirts", gender:"unisex", price:1499, mrp:2199, colors:[{name:"Cream",hex:"#F1EAD9"}], sizes:["S","M","L","XL"], stock:15, sku:"SS-SW-001", material:"400 GSM brushed fleece", care:"Wash cold inside out.", isNew:false, bestseller:true, added:"2026-01-25", popularity:92, desc:"A perfectly weighted crew with V-stitch detailing and ribbed side gussets.", details:["V-stitch","Ribbed gussets","Relaxed fit"] }),
  P({ id:"sweat-quarter-zip", name:"Trail Quarter-Zip", category:"sweatshirts", gender:"men", price:1799, mrp:2599, colors:[{name:"Espresso",hex:"#4A342E"}], sizes:["M","L","XL"], stock:8, sku:"SS-SW-002", material:"Performance double-knit", care:"Machine wash cold, hang dry.", isNew:true, bestseller:false, added:"2026-08-08", popularity:83, desc:"A polished active layer with a matte zip and stand collar. Gym to street without changing.", details:["Quarter zip","Stand collar","Moisture-wicking"] }),
  P({ id:"sweat-cropped-women", name:"Cropped Boxy Sweatshirt", category:"sweatshirts", gender:"women", price:1399, mrp:1999, colors:[{name:"Rose",hex:"#D9AFA0"}], sizes:["XS","S","M","L"], stock:12, sku:"SS-SW-003", material:"Soft loopback fleece", care:"Machine wash cold.", isNew:true, bestseller:false, added:"2026-07-18", popularity:80, desc:"Boxy and slightly cropped, with a wide rib hem that sits neatly over high-rise bottoms.", details:["Cropped boxy fit","Wide rib hem","Drop shoulder"] }),
  P({ id:"sweat-oversized-graphic", name:"Atelier Oversized Sweatshirt", category:"sweatshirts", gender:"unisex", price:1599, mrp:2399, colors:[{name:"Washed Black",hex:"#2A2A2A"}], sizes:["S","M","L","XL"], stock:3, sku:"SS-SW-004", material:"Heavy loopback, garment dyed", care:"Wash inside out, cold.", isNew:false, bestseller:false, added:"2026-04-11", popularity:72, desc:"Garment-dyed for a lived-in tone, with a tonal chest embroidery designed in our studio.", details:["Garment dyed","Tonal embroidery","Oversized fit"] }),
  P({ id:"jacket-bomber-satin", name:"Satin Souvenir Bomber", category:"jackets", gender:"women", price:3299, mrp:4799, colors:[{name:"Bottle Green",hex:"#1E4A3A"}], sizes:["XS","S","M","L"], stock:6, sku:"SS-JK-005", material:"Satin-back crepe, quilted lining", care:"Dry clean recommended.", isNew:true, bestseller:false, added:"2026-08-12", popularity:85, desc:"A lustrous bomber with minimal embroidery and a softly quilted interior for cool evenings.", details:["Quilted lining","Ribbed collar/cuffs","Relaxed fit"] }),
  P({ id:"pant-wide-palazzo", name:"Wide-Leg Crepe Pant", category:"pants", gender:"women", price:1899, mrp:2799, colors:[{name:"Black",hex:"#1E1E1E"}], sizes:["XS","S","M","L","XL"], stock:9, sku:"SS-PN-005", material:"Crepe with stretch", care:"Gentle wash, cool iron.", isNew:false, bestseller:false, added:"2026-05-27", popularity:70, desc:"Floor-skimming wide legs with a fixed waistband — fluid, flattering, endlessly wearable.", details:["Wide leg","Fixed waist","Side zip"] }),
];

export const priceAfter = (p) => p.price;
export const discountPct = (p) => p.mrp > p.price ? Math.round((1 - p.price / p.mrp) * 100) : 0;
export const inStock = (p) => (p.stock ?? 0) > 0;
export const lowStock = (p) => inStock(p) && (p.stock ?? 0) <= 5;
