require('./server/env.cjs');
const store = require('./server/store.cjs');

const indianNames = [
  "Aarav", "Vihaan", "Aditya", "Arjun", "Sai", "Riyansh", "Dhruv", "Krishna", 
  "Ananya", "Diya", "Saanvi", "Myra", "Aadhya", "Pari", "Kavya", "Ishita",
  "Rohan", "Kabir", "Aryan", "Atharv", "Pranav", "Vivaan", "Dev", "Yash",
  "Riya", "Avni", "Sara", "Neha", "Meera", "Zara", "Tara", "Naina",
  "Rahul", "Amit", "Vikram", "Suresh", "Ramesh", "Manoj", "Sanjay", "Raj",
  "Priya", "Sneha", "Pooja", "Shweta", "Kiran", "Anita", "Sunita", "Geeta",
  "Manish", "Deepak", "Akash", "Vikas", "Vishal", "Sumit", "Anil", "Sunil"
];

const positiveTitles = ["Great quality!", "Loved it", "Perfect fit", "Awesome product", "Highly recommended", "Very comfortable", "Worth the money", "Looks amazing"];
const positiveTexts = [
  "Really good quality material, feels premium.",
  "Perfect fit, exact size as mentioned in the chart.",
  "Loved the color, looks exactly like the pictures.",
  "Very comfortable to wear all day.",
  "Worth the price. highly recommended!",
  "Fabric is soft and breathable.",
  "Awesome product, arrived on time.",
  "Looks great! I've received many compliments.",
  "Stitching is top notch. Will buy more.",
  "Totally satisfied with the purchase."
];

const neutralTitles = ["Decent purchase", "Good but could be better", "Average", "Not bad", "Okay product"];
const neutralTexts = [
  "It's decent for the price, but could be slightly better.",
  "Fits okay, a little loose around the shoulders.",
  "Color is slightly lighter than the picture.",
  "Average quality, good for daily wear.",
  "Not bad, but I expected thicker fabric."
];

const negativeTitles = ["Size issue", "Not as expected", "Material could be better", "Disappointed"];
const negativeTexts = [
  "Size runs very small, had to exchange.",
  "Didn't like the material, feels a bit synthetic.",
  "After one wash, it shrunk a little.",
  "Not as premium as it looks in the photos."
];

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

(async () => {
  try {
    const products = await store.getProducts();
    let reviews = await store.getReviews();
    
    // Remove old fake reviews generated by previous script
    reviews = reviews.filter(r => !r.id.startsWith('rev_'));

    let added = 0;

    for (const product of products) {
      const needed = getRandomInt(10, 30);
      
      let prodReviews = [];
      for (let i = 0; i < needed; i++) {
        const author = indianNames[getRandomInt(0, indianNames.length - 1)]; // First name only
        
        const rand = Math.random();
        let rating, titleOptions, textOptions;
        
        // Adjust weights to ensure high average (mostly 4s and 5s)
        if (rand < 0.60) {
          rating = 5; titleOptions = positiveTitles; textOptions = positiveTexts;
        } else if (rand < 0.90) {
          rating = 4; titleOptions = positiveTitles; textOptions = positiveTexts;
        } else if (rand < 0.97) {
          rating = 3; titleOptions = neutralTitles; textOptions = neutralTexts;
        } else {
          rating = 2; titleOptions = negativeTitles; textOptions = negativeTexts;
        }
        
        const title = titleOptions[getRandomInt(0, titleOptions.length - 1)];
        const text = textOptions[getRandomInt(0, textOptions.length - 1)];
        const date = new Date(Date.now() - getRandomInt(1, 180) * 24 * 60 * 60 * 1000);
        
        prodReviews.push({
          id: "rev_" + Math.random().toString(36).substring(2, 9),
          productId: product.id,
          author: author,
          title: title,
          rating: rating,
          text: text,
          createdAt: date.toISOString()
        });
      }
      
      // Check average
      let sum = prodReviews.reduce((acc, r) => acc + r.rating, 0);
      let avg = sum / needed;
      
      // Force average >= 3.9
      while (avg < 3.9) {
        // Find a review with rating < 5 and bump it to 5
        const lowReview = prodReviews.find(r => r.rating < 5);
        if (lowReview) {
          sum += (5 - lowReview.rating);
          lowReview.rating = 5;
          lowReview.title = positiveTitles[getRandomInt(0, positiveTitles.length - 1)];
          lowReview.text = positiveTexts[getRandomInt(0, positiveTexts.length - 1)];
        }
        avg = sum / needed;
      }
      
      reviews.push(...prodReviews);
      added += prodReviews.length;
    }

    reviews.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
    await store.saveReviews(reviews);
    console.log(`Successfully added ${added} new fake Indian reviews. Total reviews: ${reviews.length}`);
  } catch (err) {
    console.error("Failed:", err);
  }
})();
